from abc import ABC, abstractmethod
from typing import Literal

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: Literal["user", "assistant"]
    content: str


class LLMRequest(BaseModel):
    system_prompt: str
    messages: list[ChatMessage]
    # A hint for providers; the rule-based demo mock uses these targets.
    target_fields: list[str] = Field(default_factory=list)


class LLMError(Exception):
    """Base exception for language-model client failures."""


class LLMConfigError(LLMError):
    """Required model configuration, such as a key or model name, is missing."""


class LLMTimeoutError(LLMError):
    """The model provider did not respond before the configured timeout."""


class LLMUnavailableError(LLMError):
    """The model provider is unavailable due to network or service errors."""


class LLMClient(ABC):
    # ######################################################
    # Function name : generate
    # Description   : Define generation of raw text from a model request.
    # Date          : 07/10/2026
    # Author        : Arya Dere
    # ######################################################
    @abstractmethod
    def generate(self, request: LLMRequest) -> str:
        """Return the raw text generated by the model."""
        raise NotImplementedError